imports:
    - { resource: 'services.yml' }

parameters:
    module_settings:
        configuration:

        hooks:
            - 'actionDispatcherBefore'

        tabs:
            - {name: 'Sirio', parent_class_name: 'AdminParentModulesSf', class_name: 'AdminSirioTab', visible: false}
            - {name: 'Info', parent_class_name: 'AdminSirioTab', class_name: 'AdminSirioInfo'}