services:
    sirio.module:
        class: 'Sirio'
        factory: ['Module', 'getInstanceByName']
        arguments:
            - 'sirio'

#    Installers
    install.tab:
        class: 'Chiron\Sirio\Install\Tab'
        arguments:
            - '%module_settings%'

    installer:
        class: 'Chiron\Sirio\Install\Installer'
        arguments:
            - '@sirio.module'
            - '%module_settings%'

    uninstaller:
        class: 'Chiron\Sirio\Install\Uninstaller'
        arguments:
            - '@sirio.module'
            - '%module_settings%'